function pl(n,variants){var cases=[2,0,1,1,1,2];return variants[(n%100>4&&n%100<20)?2:cases[Math.min(n%10,5)]]}
$(document).ready(function(){var sync1=$("#sync1");var sync2=$("#sync2");var slidesPerPage=4;var syncedSecondary=!0;sync1.owlCarousel({items:1,slideSpeed:2000,autoplay:!1,dots:!1,loop:!1,autoHeight:!0,responsive:{0:{nav:!1},1200:{nav:!0}},responsiveRefreshRate:200,navText:['<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M9 15L10.05 13.95L5.85 9.75L15 9.75L15 8.25L5.85 8.25L10.05 4.05L9 3L3 9L9 15Z" fill="#5F5F5F"/></svg>','<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M9 3L7.95 4.05L12.15 8.25H3L3 9.75H12.15L7.95 13.95L9 15L15 9L9 3Z" fill="#5F5F5F"/></svg>'],}).on('changed.owl.carousel',syncPosition);sync2
    .on('initialized.owl.carousel',function(){sync2.find(".owl-item").eq(0).addClass("current")}).owlCarousel({items:slidesPerPage,dots:!1,nav:!1,loop:!1,smartSpeed:200,slideSpeed:500,responsive:{0:{autoWidth:!0,margin:1.5},800:{autoWidth:!0,margin:2},1200:{autoWidth:!0,margin:2}},slideBy:slidesPerPage,responsiveRefreshRate:100}).on('changed.owl.carousel',syncPosition2);function syncPosition(el){var current=el.item.index;sync2
    .find(".owl-item").removeClass("current").eq(current).addClass("current");var onscreen=sync2.find('.owl-item.active').length-1;var start=sync2.find('.owl-item.active').first().index();var end=sync2.find('.owl-item.active').last().index();if(current>end){sync2.data('owl.carousel').to(current,100,!0)}
    if(current<start&&window.innerWidth<1200){sync2.data('owl.carousel').to(current-onscreen,100,!0)}}
    function syncPosition2(el){if(syncedSecondary){let number=el.item.index;sync1.data('owl.carousel').to(number,100,!0)}}
    sync2.on("click",".owl-item",function(e){e.preventDefault();let number=$(this).index();sync1.data('owl.carousel').to(number,300,!0)})});$.fancybox.defaults.buttons=["zoom","thumbs","close"];$('.product__slider .show-more').on('click',function(e){e.preventDefault();e.stopPropagation();if($(this).attr('data-expanded')==='false'){$('.product__slider .thumbs-carousel .owl-stage').addClass('expanded')
    $(this).attr('data-expanded','true')}else{$('.product__slider .thumbs-carousel .owl-stage').removeClass('expanded')
    $(this).attr('data-expanded','false')}});if($('.product__slider .if-sticky')&&window.innerWidth>1200){let prod_head=$('.if-sticky').outerHeight();$('.if-sticky').css('margin-top',-prod_head+'px')}
$(document).on('scroll',function(){let elem=document.querySelector('.product__description__row .product__price-block'),bounding=elem.getBoundingClientRect();if(bounding.top<0&&!$('.product__fixed-actions').hasClass('displayed')){$('.product__fixed-actions').addClass('displayed')}else if(bounding.top>0){$('.product__fixed-actions').removeClass('displayed')}});$('.product__mark img').popover({html:!0,placement:'bottom',trigger:'hover',offset:'-40, 0',template:'<div class="popover product-mark-popover" role="tooltip"><div class="arrow"></div><h3 class="popover-header"></h3><div class="popover-body"></div></div>'});$('.product__more-data-desktop .nav a').on('click',function(e){e.preventDefault();e.stopPropagation();let view=$('.product__more-data-desktop .view'),ref=$(this).attr('href');view.find('.view-content').hide();$('.product__more-data-desktop .nav a').removeClass('--active');view.find('.view-content'+ref).show();$(this).addClass('--active')})
let sm_link=$('.product__characteristics .show-more'),sm_container=$('.product__characteristics__container');sm_link.on('click',function(e){e.preventDefault();e.stopPropagation();if(sm_container.hasClass('expanded')){sm_container.removeClass('expanded');sm_link.attr('aria-expanded','false')}else{sm_container.addClass('expanded');sm_link.attr('aria-expanded','true')}})
let money_input=$('#range-money'),time_input=$('#range-time'),price=+$('.product .product__price-block .main').text().replace(/\s/g,'').replace(/в‚Ѕ/g,''),range_money_control=document.getElementById('range-money-control'),range_time_control=document.getElementById('range-time-control');var creditCalc={_months:{min:24,max:84,step:12,start:60,tickStep:12},_first:{min:0,max:90,step:1,start:50,tickStep:30},months:60,first:50,price:productPrice,total:productPrice*0.5,monthly:Math.round(productPrice*0.5*(60*0.01+1)/60),calc:function(){this.total=Math.round(this.price*(1-this.first*0.01));this.monthly=Math.round(this.total*(this.months*0.01+1)/this.months);return this.monthly},update:function(){this.calc();$('.ecredit.main').data({initial_fee_money:Math.round(productPrice*this.first*0.01),});$('#cc-total').html(this.total+' &#x20bd;');$('#cc-monthly').html(this.monthly+' &#x20bd;')}}
noUiSlider.create(range_money_control,{start:creditCalc._first.start,connect:[!0,!1],step:creditCalc._first.step,range:{'min':creditCalc._first.min,'max':creditCalc._first.max}});range_money_control.noUiSlider.on('update',function(values,handle){var percent=values[handle]*0.01,val=percent*productPrice;money_input.val(parseInt(val).toFixed(2).replace(/\d(?=(\d{3})+\.)/g,'$& ').replace('.00','')+' в‚Ѕ');creditCalc.first=parseInt(values[handle]);creditCalc.update()});noUiSlider.create(range_time_control,{start:creditCalc._months.start,connect:[!0,!1],step:creditCalc._months.step,range:{'min':creditCalc._months.min,'max':creditCalc._months.max}});range_time_control.noUiSlider.on('update',function(values,handle){time_input.val(parseInt(values[handle])+' '+pl(parseInt(values[handle]),['РјРµСЃСЏС†','РјРµСЃСЏС†Р°','РјРµСЃСЏС†РµРІ']));creditCalc.months=parseInt(values[handle]);creditCalc.update()});money_input.on('focusin',function(){$(this).val('')})
money_input.on('focusout',function(e){if($(this).val()===''||isNaN($(this).val())){range_money_control.noUiSlider.set(range_money_control.noUiSlider.value)}else if($(this).val()<parseInt(price*.1)){range_money_control.noUiSlider.set(0)}else if($(this).val()>parseInt(price*.9)){range_money_control.noUiSlider.set(99999999999)}else{let val=parseInt(+e.target.value);range_money_control.noUiSlider.set(val)}})
time_input.on('focusin',function(){$(this).val('')}).on('focusout',function(e){if($(this).val()===''||isNaN($(this).val())){range_time_control.noUiSlider.set(range_time_control.noUiSlider.value)}else if($(this).val()<12){range_time_control.noUiSlider.set(12)}else if($(this).val()>84){range_time_control.noUiSlider.set(84)}else{let val=e.target.value;range_time_control.noUiSlider.set(val)}})
$(function(){var $timeticks=$('.ticks',$(range_time_control).parent()).html('');for(var i=creditCalc._months.min;i<=creditCalc._months.max;i+=creditCalc._months.tickStep)
    $timeticks.append('<div class="tick">'+i+'</div>');var $firstticks=$('.ticks',$(range_money_control).parent()).html('');for(var i=creditCalc._first.min;i<=creditCalc._first.max;i+=creditCalc._first.tickStep)
    $firstticks.append('<div class="tick">'+i+'%</div>');})
let sameSlider=$('.product__look-a-like-slider .owl-carousel');let recentSlider=$('.product__recent-views-slider .owl-carousel');sameSlider.owlCarousel({items:4,margin:2,dots:!1,responsive:{0:{items:1.73,autoWidth:!0,slideBy:1},800:{items:2.5,autoWidth:!0,slideBy:3},1200:{items:5,slideBy:3,nav:!0,navText:['<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M9 15L10.05 13.95L5.85 9.75L15 9.75L15 8.25L5.85 8.25L10.05 4.05L9 3L3 9L9 15Z" fill="#5F5F5F"/></svg>','<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M9 3L7.95 4.05L12.15 8.25H3L3 9.75H12.15L7.95 13.95L9 15L15 9L9 3Z" fill="#5F5F5F"/></svg>'],},}});recentSlider.owlCarousel({items:4,margin:2,dots:!1,responsive:{0:{items:1.73,autoWidth:!0,slideBy:1},800:{items:2.5,autoWidth:!0,slideBy:3},1200:{items:5,slideBy:3,nav:!0,navText:['<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M9 15L10.05 13.95L5.85 9.75L15 9.75L15 8.25L5.85 8.25L10.05 4.05L9 3L3 9L9 15Z" fill="#5F5F5F"/></svg>','<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M9 3L7.95 4.05L12.15 8.25H3L3 9.75H12.15L7.95 13.95L9 15L15 9L9 3Z" fill="#5F5F5F"/></svg>'],},}});$(function(){$(document).on('click','.action.share',function(){$('#share').popover('show');return!1});$(document).on('click','.action.fav',function(){var $btn=$(this),action=$(this).is('.un')?'unfav':'fav';$.post('/action/'+action,{id:$(this).data('id')},function(rsp){if(rsp.success){(action=='fav')?$btn.addClass('un'):$btn.removeClass('un')}else alert(rsp.message)},'json');return!1})})